_wandb:
    value:
        cli_version: 0.22.1
        e:
            9e2flmx1hndcdub03ndeg8jztvarm6py:
                apple:
                    ecpuCores: 6
                    gpuCores: 10
                    memoryGb: 24
                    name: Apple M4
                    pcpuCores: 4
                    ramTotalBytes: "25769803776"
                args:
                    - trainer.max_epochs=5
                    - tracker.use_wandb=8cf1de46a6e295f88f9538ade5d7cddc470ed73c
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "994662584320"
                        used: "131174252544"
                email: marshallgfx7@gmail.com
                executable: /Users/marshall/Projects/DLToolKit/.venv/bin/python3
                git:
                    commit: 6b276bc69925d378da514dd1e1157d5e2e47d677
                    remote: git@github.com:Marshall-Ge/DLToolKit.git
                host: Mac
                memory:
                    total: "25769803776"
                os: macOS-26.0.1-arm64-arm-64bit
                program: -m dltoolkit.trainer.img_cls
                python: CPython 3.12.11
                root: /Users/marshall/Projects/DLToolKit
                startedAt: "2025-10-07T04:32:29.559648Z"
                writerId: 9e2flmx1hndcdub03ndeg8jztvarm6py
        m:
            - "1": train/global_step
              "6":
                - 3
              "7": []
            - "1": eval/global_step
              "6":
                - 3
              "7": []
            - "2": train/*
              "5": 1
              "6":
                - 1
              "7": []
            - "2": eval/*
              "5": 2
              "6":
                - 1
              "7": []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 50
                - 51
                - 53
                - 71
                - 105
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 50
                - 51
                - 53
                - 71
                - 105
            "3":
                - 2
                - 7
                - 13
                - 16
                - 66
            "4": 3.12.11
            "5": 0.22.1
            "6": 4.56.1
            "10":
                - 20
            "12": 0.22.1
            "13": darwin-arm64
ckpt_path:
    value: ./ckpt/img_cls/
data:
    value: '{''num_classes'': 10, ''image_key'': ''image'', ''text_key'': ''label'', ''name_or_path'': ''ylecun/mnist'', ''split'': ''train'', ''eval_dataset'': None, ''eval_split'': None, ''probs'': ''1.0'', ''max_samples'': None, ''max_len'': None, ''input_template'': None, ''drop_last'': False, ''img_transform'': {''type'': ''default''}}'
load_checkpoint:
    value: "True"
max_ckpt_mem:
    value: "1000"
max_ckpt_num:
    value: "3"
model:
    value: '{''name_or_path'': ''CovNet_MNIST'', ''param'': {}}'
optim:
    value: '{''type'': ''AdamW'', ''betas'': [0.9, 0.999], ''weight_decay'': 0.01}'
save_path:
    value: ./ckpt/
seed:
    value: "42"
strategy:
    value: '{''mixed_precision'': None}'
tracker:
    value: '{''use_wandb'': ''8cf1de46a6e295f88f9538ade5d7cddc470ed73c'', ''wandb_project'': ''dltoolkit'', ''wandb_run_name'': ''img_cls'', ''wandb_org'': None, ''wandb_group'': ''img_cls_experiments'', ''use_tensorboard'': ''./logs/''}'
trainer:
    value: '{''train_batch_size'': 256, ''max_epochs'': 5, ''lr_scheduler'': ''cosine_with_min_lr'', ''learning_rate'': 0.001, ''lr_warmup_ratio'': 0.03, ''loss'': ''cross_entropy'', ''eval_steps'': -1, ''save_steps'': -1, ''log_steps'': 1}'
use_ms:
    value: "False"
