ROOT=E:/PROJECTS/DLToolBox/
CKPT=E:/PROJECTS/DLToolBox/ckpt_files

cd $ROOT

TRAIN_FILE=captions_train2017.json
VAL_FILE=captions_val2017.json
TEST_FILE=captions_val2017.json

TORCH_DISTRIBUTED_DEBUG=INFO python -W ignore -u main.py \
  --cfg configs/coco/CLIP_VIT16_COCO_CAPTION.yaml \
  --opts DATA.PATH_TO_DATA_DIR E:/DATASETS/COCO-Caption/annotations \
  DATA.PATH_TO_METADATA_DIR E:/DATASETS/COCO-Caption/ \
  TRAIN_FILE $TRAIN_FILE \
  VAL_FILE $VAL_FILE \
  TEST_FILE $TEST_FILE \
  TRAIN.ENABLE True \
  OUTPUT_DIR $CKPT/ \
  TRAIN.BATCH_SIZE 64 \
  TEST.BATCH_SIZE 240 \
  NUM_GPUS 1 \
  SOLVER.MAX_EPOCH 10 \
  SOLVER.WARMUP_EPOCHS 2.0 \
  SOLVER.BASE_LR 3.33e-6 \
  SOLVER.WARMUP_START_LR 3.33e-8 \
  SOLVER.COSINE_END_LR 3.33e-8 \
  TRAIN.EVAL_PERIOD 22 \
  TRAIN.CHECKPOINT_PERIOD 1 \
  MODEL.LOSS_FUNC mse \
  TRAIN.CLIP_ORI_PATH /root/.cache/clip/ViT-B-16.pt \
